"""ScholarFlow Stage 0 Preset Dimensions for Research Skills.

Provides standard GrillDimension definitions for:
- literature-discovery-acquisition (D1 - D14)
- literature-evidence-extraction (E1 - E9)
- literature-synthesis (S1 - S11)
"""

from shared.grill_me.response_parser import (
    DimensionOption,
    GrillDimension,
    PriorityTier,
)


def get_discovery_dimensions() -> list[GrillDimension]:
    return [
        GrillDimension(
            id="D1",
            name="研究目标与产出定位",
            priority=PriorityTier.CRITICAL,
            description="明确本轮文献发现的具体科研目标与成果承接形式。",
            options=[
                DimensionOption("A", "学位论文开题 / 领域系统综述背景调研", is_recommended=True,
                                rationale="全面覆盖领域脉络，保证高召回与可审计性", confidence="high", value="systematic_survey"),
                DimensionOption("B", "特定技术路线 / 实验方案对比选型",
                                rationale="针对具体实验协议与参数", confidence="moderate", value="protocol_selection"),
                DimensionOption("C", "前沿学术争议 / 竞争假说事实核查",
                                rationale="聚焦对立学派的争鸣文献", confidence="moderate", value="controversy_screening"),
            ],
            default_key="A",
            default_value="systematic_survey",
        ),
        GrillDimension(
            id="D2",
            name="核心研究问题与因果命题",
            priority=PriorityTier.CRITICAL,
            description="明确本次调研的核心科研科学假说或因果判定焦点。",
            options=[
                DimensionOption("A", "探索性机制/因果关联命题（关注前因后果与调节变量）", is_recommended=True,
                                rationale="因果机制研究最具学术综合价值", confidence="high", value="causal_mechanism"),
                DimensionOption("B", "现状与基线评估（关注时空分布、丰度或参数现状）",
                                rationale="描述性或基线调查适用", confidence="moderate", value="baseline_survey"),
                DimensionOption("C", "方法学有效性验证（关注新旧方法评测与误差对比）",
                                rationale="纯方法评估适用", confidence="moderate", value="method_benchmarking"),
            ],
            default_key="A",
            default_value="causal_mechanism",
        ),
        GrillDimension(
            id="D3",
            name="目标实体与概念范畴",
            priority=PriorityTier.CRITICAL,
            description="界定研究所涉及的物种、靶点、算法、化学物或学科实体范围。",
            options=[
                DimensionOption("A", "严格限定于单一目标实体（及其同义词/分类变更名）", is_recommended=True,
                                rationale="保证文献精准度，杜绝无关跨领域扩散", confidence="high", value="strict_single_entity"),
                DimensionOption("B", "包含近缘实体/同族比较实体（如近缘属种或同类靶点）",
                                rationale="在单一实体文献匮乏时扩展边界", confidence="moderate", value="sister_taxa_included"),
                DimensionOption("C", "泛化至同类方法/通用范式全集",
                                rationale="仅关注通用方法本身", confidence="low", value="method_general"),
            ],
            default_key="A",
            default_value="strict_single_entity",
        ),
        GrillDimension(
            id="D4",
            name="纳入标准与边界",
            priority=PriorityTier.CRITICAL,
            description="界定哪些文献具备入选资格的底层学术逻辑。",
            options=[
                DimensionOption("A", "具备完整实证数据、明确实验/调查设计与定量结论", is_recommended=True,
                                rationale="确保后续提取与合成具备实证基础", confidence="high", value="empirical_quantitative"),
                DimensionOption("B", "包含理论推导、概念模型与评论性观点",
                                rationale="偏重理论综述时适用", confidence="moderate", value="theoretical_conceptual"),
                DimensionOption("C", "全谱高召回（只要提及关键词即粗筛纳入）",
                                rationale="极度冷门或早期摸索适用", confidence="low", value="broad_recall"),
            ],
            default_key="A",
            default_value="empirical_quantitative",
        ),
        GrillDimension(
            id="D5",
            name="排除标准与禁忌红线",
            priority=PriorityTier.CRITICAL,
            description="一票否决的不合格文献过滤红线。",
            options=[
                DimensionOption("A", "排除纯新闻科普、无数据评论、低质量掠夺性期刊及非同行评议预印本", is_recommended=True,
                                rationale="严守学术质量门禁，剔除高噪声与未验证结论", confidence="high", value="strict_peer_reviewed"),
                DimensionOption("B", "允许高质量预印本（如顶级机构挂靠），但排除通俗科普",
                                rationale="前沿新兴领域适用", confidence="moderate", value="allow_vetted_preprints"),
                DimensionOption("C", "仅排除纯商业广告与完全不相干学科",
                                rationale="最低过滤门槛", confidence="low", value="minimal_filter"),
            ],
            default_key="A",
            default_value="strict_peer_reviewed",
        ),
        GrillDimension(
            id="D6",
            name="概念拓展与近义词策略",
            priority=PriorityTier.HIGH_IMPACT,
            description="检索表达式中同义词、布尔逻辑与上位概念构建方案。",
            options=[
                DimensionOption("A", "标准概念矩阵构建（核心词 + 英文正名/曾用名 + 缩写 + 核心方法）", is_recommended=True,
                                rationale="PRISMA-S 规范推荐，平衡查全率与查准率", confidence="high", value="concept_matrix"),
                DimensionOption("B", "极简核心词检索（仅使用最标准关键词）",
                                rationale="快速探测文献量级", confidence="moderate", value="strict_keywords"),
            ],
            default_key="A",
            default_value="concept_matrix",
        ),
        GrillDimension(
            id="D7",
            name="地理与空间范畴",
            priority=PriorityTier.HIGH_IMPACT,
            description="文献研究对象的地域或空间尺度限制。",
            options=[
                DimensionOption("A", "不设地理限制（全球文献，关注普适性机制与规律）", is_recommended=True,
                                rationale="国际科学研究通用偏好", confidence="high", value="global"),
                DimensionOption("B", "限定于特定国家/地理区域/生态大区",
                                rationale="区域性生态或政策研究适用", confidence="moderate", value="regional"),
            ],
            default_key="A",
            default_value="global",
        ),
        GrillDimension(
            id="D8",
            name="时间跨度与历史回溯",
            priority=PriorityTier.HIGH_IMPACT,
            description="文献发表年份边界与经典论文回溯原则。",
            options=[
                DimensionOption("A", "近 10 年前沿为主 + 领域奠基性经典文献追溯", is_recommended=True,
                                rationale="平衡前沿动态与理论源头", confidence="high", value="recent_10y_plus_foundational"),
                DimensionOption("B", "近 5 年极高前沿（专注于最新进展）",
                                rationale="适用于 AI / 基因编辑等爆发期学科", confidence="moderate", value="recent_5y"),
                DimensionOption("C", "全历史无截断（完全不设时间下限）",
                                rationale="学科通史调研适用", confidence="moderate", value="all_time"),
            ],
            default_key="A",
            default_value="recent_10y_plus_foundational",
        ),
        GrillDimension(
            id="D9",
            name="文献类型与同行评审门槛",
            priority=PriorityTier.HIGH_IMPACT,
            description="期刊长文、会议、博硕论文、专利等文献类型优先级。",
            options=[
                DimensionOption("A", "同行评审学术期刊研究论文 (Research Articles) 优先", is_recommended=True,
                                rationale="科研证据金标准", confidence="high", value="peer_reviewed_articles"),
                DimensionOption("B", "期刊论文 + 权威博硕士学位论文 + 顶会论文",
                                rationale="增加未完全发表细节补充", confidence="moderate", value="articles_theses_conferences"),
            ],
            default_key="A",
            default_value="peer_reviewed_articles",
        ),
        GrillDimension(
            id="D10",
            name="语言范围与多语种策略",
            priority=PriorityTier.DEFAULTABLE,
            description="文献收录语言要求。",
            options=[
                DimensionOption("A", "英文国际主流文献 + 中文核心期刊", is_recommended=True,
                                rationale="覆盖国际权威与本土重要成果", confidence="high", value="en_and_zh"),
                DimensionOption("B", "仅限英文文献", rationale="国际前沿课题", confidence="moderate", value="en_only"),
            ],
            default_key="A",
            default_value="en_and_zh",
        ),
        GrillDimension(
            id="D11",
            name="种子文献与滚雪球起点",
            priority=PriorityTier.DEFAULTABLE,
            description="是否具备可供 Citation Chasing 的代表性基石文献。",
            options=[
                DimensionOption("A", "自动在初筛命中中聚类被引最高的核心文章作为种子", is_recommended=True,
                                rationale="自动化高召回标准做法", confidence="high", value="auto_seed_clustering"),
                DimensionOption("B", "由用户指定 1~3 篇已知种子文献展开正反向追踪",
                                rationale="用户已有基石论文时推荐", confidence="moderate", value="user_specified_seeds"),
            ],
            default_key="A",
            default_value="auto_seed_clustering",
        ),
        GrillDimension(
            id="D12",
            name="数据库边界与工具链偏好",
            priority=PriorityTier.DEFAULTABLE,
            description="优先调用的学术检索源及 Open Access 渠道。",
            options=[
                DimensionOption("A", "OpenAlex + Europe PMC + PubMed + arXiv/bioRxiv 多源聚合", is_recommended=True,
                                rationale="最大化免费合规开放获取率", confidence="high", value="multi_source_oa"),
                DimensionOption("B", "纯单一库聚焦检索", rationale="极窄范围测试", confidence="low", value="single_db"),
            ],
            default_key="A",
            default_value="multi_source_oa",
        ),
        GrillDimension(
            id="D13",
            name="检索深度与饱和度停止条件",
            priority=PriorityTier.DEFAULTABLE,
            description="引用追溯层数与边际递减终止阈值。",
            options=[
                DimensionOption("A", "2 层追溯；连续 20 篇新增文献中无新概念时达到饱和终止", is_recommended=True,
                                rationale="符合 PRISMA 饱和度科学停止标准", confidence="high", value="depth_2_saturation"),
                DimensionOption("B", "单层直接检索（不滚雪球）", rationale="快速粗查", confidence="moderate", value="single_pass"),
            ],
            default_key="A",
            default_value="depth_2_saturation",
        ),
        GrillDimension(
            id="D14",
            name="交付物类型与下游承接",
            priority=PriorityTier.DEFAULTABLE,
            description="初筛清单输出格式与下游工具无缝承接方式。",
            options=[
                DimensionOption("A", "PRISMA 结构化初筛台账 + 全文下载清单 + 概念矩阵", is_recommended=True,
                                rationale="无缝输入下游证据抽取与 Zotero", confidence="high", value="prisma_ledger_oa_links"),
            ],
            default_key="A",
            default_value="prisma_ledger_oa_links",
        ),
    ]


def get_extraction_dimensions() -> list[GrillDimension]:
    return [
        GrillDimension(
            id="E1",
            name="抽取目的与任务类型",
            priority=PriorityTier.CRITICAL,
            description="明确本次证据抽取的下游科研用途与严谨性级别。",
            options=[
                DimensionOption("A", "系统综述 / Meta 分析结构化参数与定量数据提取", is_recommended=True,
                                rationale="遵循标准循证医学与生态学循证标准", confidence="high", value="meta_analysis_params"),
                DimensionOption("B", "特定论文事实核验（Claim Audit 模式）",
                                rationale="对照文献审核既有结论真实性", confidence="moderate", value="claim_audit"),
                DimensionOption("C", "方法学与实验协议关键参数对比",
                                rationale="提炼各文献实验步骤与试剂", confidence="moderate", value="protocol_extraction"),
            ],
            default_key="A",
            default_value="meta_analysis_params",
        ),
        GrillDimension(
            id="E2",
            name="待抽取的文献范围与输入边界",
            priority=PriorityTier.CRITICAL,
            description="明确本次提取的对象文献集与文本形态。",
            options=[
                DimensionOption("A", "初筛合格的全文 PDF / 权威解析全文文本", is_recommended=True,
                                rationale="保证表格、附录与正文方法完整可见", confidence="high", value="fulltext_pdf"),
                DimensionOption("B", "仅限公开的摘要 (Abstract) 与标题粗提",
                                rationale="缺乏全文时的降级粗提", confidence="low", value="abstract_only"),
            ],
            default_key="A",
            default_value="fulltext_pdf",
        ),
        GrillDimension(
            id="E3",
            name="抽取 Schema 选择与定制",
            priority=PriorityTier.CRITICAL,
            description="确定采用的标准抽取模式与字段集合。",
            options=[
                DimensionOption("A", "通用实证研究双轨 Schema (schemas/v1.0/general_empirical.json)", is_recommended=True,
                                rationale="内置 E1-E4 证据隔离与事实/解释分层", confidence="high", value="general_empirical_v1"),
                DimensionOption("B", "生物医药临床干预 Schema (schemas/v1.0/biomedical_intervention.json)",
                                rationale="PICO 与效应量专属字段", confidence="high", value="biomedical_v1"),
                DimensionOption("C", "生态种群与野外调查 Schema (schemas/v1.0/ecological_population.json)",
                                rationale="栖息地、种群参数与分子标记专属字段", confidence="high", value="ecological_v1"),
            ],
            default_key="A",
            default_value="general_empirical_v1",
        ),
        GrillDimension(
            id="E4",
            name="证据单元切分与多实验隔离粒度",
            priority=PriorityTier.CRITICAL,
            description="同一篇文献中包含多个独立实验/处理组时的拆分规则。",
            options=[
                DimensionOption("A", "细粒度拆分：每个独立 Assay/Trial/采样地单独形成一行记录", is_recommended=True,
                                rationale="防止条件混淆，保证定量效应量精确可比", confidence="high", value="fine_grained_assay"),
                DimensionOption("B", "整篇文献单条记录（仅提取主要全局综合结论）",
                                rationale="宏观总结时适用", confidence="low", value="study_level_coarse"),
            ],
            default_key="A",
            default_value="fine_grained_assay",
        ),
        GrillDimension(
            id="E5",
            name="推导证据与重计算策略",
            priority=PriorityTier.HIGH_IMPACT,
            description="文献未直接给出但在正文中提供原始数据时的计算规范。",
            options=[
                DimensionOption("A", "允许透明重计算（必须附带明确公式、原始输入与计算代码）", is_recommended=True,
                                rationale="提高数据可用性并确保完全可审计", confidence="high", value="transparent_recalculation"),
                DimensionOption("B", "严禁任何计算，仅提取作者字面显式陈述的原值",
                                rationale="极度保守审计模式", confidence="moderate", value="verbatim_only"),
            ],
            default_key="A",
            default_value="transparent_recalculation",
        ),
        GrillDimension(
            id="E6",
            name="计量单位与数值归一化要求",
            priority=PriorityTier.HIGH_IMPACT,
            description="跨文献异构单位（如 mg/L vs mol/L，个/km² vs 个/ha）的换算规则。",
            options=[
                DimensionOption("A", "保留原文原始数值与单位，并在标准列并列给出 SI 国际标准换算值", is_recommended=True,
                                rationale="兼顾原文核对与后续横向定量合成", confidence="high", value="dual_unit_normalization"),
                DimensionOption("B", "仅保留作者原文单位", rationale="不对数值做任何转换", confidence="moderate", value="raw_units"),
            ],
            default_key="A",
            default_value="dual_unit_normalization",
        ),
        GrillDimension(
            id="E7",
            name="表格与附录补充材料处理策略",
            priority=PriorityTier.DEFAULTABLE,
            description="核心数据散落在 Supplementary Materials 时的处理策略。",
            options=[
                DimensionOption("A", "优先深入挖掘附录与表格正文，附录与正文冲突时以详尽表格为准", is_recommended=True,
                                rationale="高精定量参数绝大多数沉淀在附录与大表", confidence="high", value="supplement_priority"),
                DimensionOption("B", "仅提取正文主体内容，忽略外部补充附件",
                                rationale="节省处理带宽", confidence="low", value="main_text_only"),
            ],
            default_key="A",
            default_value="supplement_priority",
        ),
        GrillDimension(
            id="E8",
            name="事实核验与解释边界",
            priority=PriorityTier.DEFAULTABLE,
            description="作者 Discussion 中的主观推论与 Results 实测事实的隔离规则。",
            options=[
                DimensionOption("A", "严格执行 Quote-before-Extract，将客观 Findings 与主观 Interpretations 物理隔离", is_recommended=True,
                                rationale="ScholarFlow 核心可信抽取铁律", confidence="high", value="strict_quote_separation"),
            ],
            default_key="A",
            default_value="strict_quote_separation",
        ),
        GrillDimension(
            id="E9",
            name="批量一致性与抽检策略",
            priority=PriorityTier.DEFAULTABLE,
            description="多文献并行提取的质量抽查比例。",
            options=[
                DimensionOption("A", "完成批次后执行 10% 随机高危字段（置信区间、p值、样本量）人工式对齐审计", is_recommended=True,
                                rationale="发现模型幻觉与数字转录错位的标准 QC 机制", confidence="high", value="ten_percent_spot_check"),
            ],
            default_key="A",
            default_value="ten_percent_spot_check",
        ),
    ]


def get_synthesis_dimensions() -> list[GrillDimension]:
    return [
        GrillDimension(
            id="S1",
            name="综合目的与产出定位",
            priority=PriorityTier.CRITICAL,
            description="界定跨篇文献合成的核心目标与呈现样式。",
            options=[
                DimensionOption("A", "全景学术争议诊断与学派演进图谱 (Controversy & School Mapping)", is_recommended=True,
                                rationale="揭示前沿学术争鸣与底层范式分歧的标准产出", confidence="high", value="controversy_school_mapping"),
                DimensionOption("B", "共识度分级与边界标定 (Consensus Level Rating)",
                                rationale="侧重于梳理公认结论与不确定性", confidence="moderate", value="consensus_rating"),
                DimensionOption("C", "争议驱动型叙事综述 (Narrative Review)",
                                rationale="生成可直接嵌入学位论文开题/引言的综述章节", confidence="high", value="narrative_review"),
            ],
            default_key="A",
            default_value="controversy_school_mapping",
        ),
        GrillDimension(
            id="S2",
            name="核心争鸣命题与待检验假设",
            priority=PriorityTier.CRITICAL,
            description="本次交叉对比所围绕的中心命题或竞争性假说。",
            options=[
                DimensionOption("A", "因果效应方向分歧（如：干预/变量究竟起到促进还是抑制作用）", is_recommended=True,
                                rationale="最典型且最富启发性的核心学术冲突", confidence="high", value="direction_conflict"),
                DimensionOption("B", "数值量级与阈值分歧（如：有效剂量、承载力临界点等定量争鸣）",
                                rationale="方向一致但效应量差异巨大的争议", confidence="moderate", value="magnitude_dispute"),
                DimensionOption("C", "机制模型与解释范式竞争（如：结构模型 vs 行为模型）",
                                rationale="理论底层机理解释的对立", confidence="moderate", value="mechanistic_rivalry"),
            ],
            default_key="A",
            default_value="direction_conflict",
        ),
        GrillDimension(
            id="S3",
            name="证据库来源与纳入边界",
            priority=PriorityTier.CRITICAL,
            description="用于合成分析的输入证据集范围。",
            options=[
                DimensionOption("A", "经过 Extraction 严格质控与审计的结构化证据表 (E1-E4 完备)", is_recommended=True,
                                rationale="保证跨文献比较建立在可靠事实之上", confidence="high", value="audited_extraction_table"),
                DimensionOption("B", "包含未经细粒度提取的文献全文集合（现场提取并合成）",
                                rationale="轻量快速探索适用", confidence="low", value="on_the_fly_synthesis"),
            ],
            default_key="A",
            default_value="audited_extraction_table",
        ),
        GrillDimension(
            id="S4",
            name="比较单元与聚合粒度",
            priority=PriorityTier.CRITICAL,
            description="横向对比分析的基本单位划分。",
            options=[
                DimensionOption("A", "以独立实验/独立研究点为单元对比（细粒度）", is_recommended=True,
                                rationale="消除篇内异质性，避免将同一篇论文中不同对照组笼统归纳", confidence="high", value="assay_level"),
                DimensionOption("B", "以单篇文献总体结论为单元对比（篇章粒度）",
                                rationale="宏观文献计量风格", confidence="moderate", value="paper_level"),
            ],
            default_key="A",
            default_value="assay_level",
        ),
        GrillDimension(
            id="S5",
            name="可比性边界与条件控制",
            priority=PriorityTier.HIGH_IMPACT,
            description="跨文献异构实验条件下的横向可比性准入基线。",
            options=[
                DimensionOption("A", "按核心混杂变量（如实验系统、测量时间点、剂量梯度）分层后再对比", is_recommended=True,
                                rationale="防止出现辛普森悖论与假争议", confidence="high", value="stratified_comparison"),
                DimensionOption("B", "跨条件直接合并总体对比", rationale="仅在研究高度标准化时适用", confidence="low", value="direct_pooling"),
            ],
            default_key="A",
            default_value="stratified_comparison",
        ),
        GrillDimension(
            id="S6",
            name="证据质量评级与加权策略",
            priority=PriorityTier.HIGH_IMPACT,
            description="对不同来源证据赋予权重的评价规则。",
            options=[
                DimensionOption("A", "多维循证质量加权（根据样本量、研究设计、偏倚风险等级赋予置信权重）", is_recommended=True,
                                rationale="循证综合 Gold Standard，防止低质文献左右结论", confidence="high", value="quality_weighted"),
                DimensionOption("B", "等权重民主计数（一文一票）",
                                rationale="简单频次统计，存在质量稀释风险", confidence="low", value="equal_weight"),
            ],
            default_key="A",
            default_value="quality_weighted",
        ),
        GrillDimension(
            id="S7",
            name="学派识别与聚类灵敏度",
            priority=PriorityTier.HIGH_IMPACT,
            description="判定不同学术阵营和理论学派的聚合门槛。",
            options=[
                DimensionOption("A", "依据核心机制假设与方法学传统进行聚类（9类学术争议分类法）", is_recommended=True,
                                rationale="深入揭示学科分歧的深层理论根源", confidence="high", value="taxonomy_9types"),
                DimensionOption("B", "依据作者合著网络与引用社区聚类",
                                rationale="文献计量学视角", confidence="moderate", value="citation_community"),
            ],
            default_key="A",
            default_value="taxonomy_9types",
        ),
        GrillDimension(
            id="S8",
            name="时间演进与范式转移切片",
            priority=PriorityTier.DEFAULTABLE,
            description="是否按时间线切分理论演进阶段（如早期探索期、范式确立期、反思期）。",
            options=[
                DimensionOption("A", "按时间窗口划分阶段，标注关键里程碑文献与结论演变", is_recommended=True,
                                rationale="展现学科知识进化轨迹", confidence="high", value="temporal_windows"),
                DimensionOption("B", "静态截面分析（忽略时间先后顺序）", rationale="纯横向对比", confidence="low", value="static_snapshot"),
            ],
            default_key="A",
            default_value="temporal_windows",
        ),
        GrillDimension(
            id="S9",
            name="反方辩驳与异见证据策略",
            priority=PriorityTier.DEFAULTABLE,
            description="独立 Gatekeeper / Devil's Advocate 对主流观点的审视机制。",
            options=[
                DimensionOption("A", "强制启动独立反方挑刺（Devil's Advocate 审计），挖掘潜在反例与局限", is_recommended=True,
                                rationale="ScholarFlow 独创防回音室与证实偏差机制", confidence="high", value="mandatory_devils_advocate"),
            ],
            default_key="A",
            default_value="mandatory_devils_advocate",
        ),
        GrillDimension(
            id="S10",
            name="知识空白与上游反馈机制",
            priority=PriorityTier.DEFAULTABLE,
            description="当发现证据链断裂或关键缺失时，向检索/抽取阶段派发补齐任务的规则。",
            options=[
                DimensionOption("A", "生成标准 Upstream Gap Request 结构化任务包反馈上游", is_recommended=True,
                                rationale="形成研发生态闭环", confidence="high", value="upstream_gap_request"),
            ],
            default_key="A",
            default_value="upstream_gap_request",
        ),
        GrillDimension(
            id="S11",
            name="叙事综述产出深度",
            priority=PriorityTier.DEFAULTABLE,
            description="综述文本的深度与风格。",
            options=[
                DimensionOption("A", "学术论文级别深度，段落围绕 Claims 组织并标注证据等级与争议点", is_recommended=True,
                                rationale="可直接用于高水平学术写作与发表", confidence="high", value="claims_first_narrative"),
            ],
            default_key="A",
            default_value="claims_first_narrative",
        ),
    ]
