"""ScholarFlow Version and Canonical Specification Constants."""

__version__ = "0.6.3"
PROJECT_VERSION = "0.6.3"

CONTRACT_SPEC_VERSION = "1.1"
SCHEMA_VERSION = "1.1"  # For backward compatibility

DISCOVERY_RESULT_SCHEMA_VERSION = "1.1"
EXTRACTION_RESULT_SCHEMA_VERSION = "1.1"

LITERATURE_RECORD_SCHEMA_VERSION = "1.0"
EVIDENCE_RECORD_SCHEMA_VERSION = "1.0"
CLAIM_RECORD_SCHEMA_VERSION = "1.0"
SYNTHESIS_RECORD_SCHEMA_VERSION = "1.0"

BENCHMARK_SUITE_VERSION = "0.1"
